#!/bin/bash

# http://lucene.apache.org/core/old_versioned_docs/versions/3_5_0/queryparsersyntax.html
# http://<host>:<port>/[index]/[type]/[_action/id]
yourIP=$(hostname -I | cut -d' ' -f1);
yourIP=${yourIP:=127.0.0.1};

NAME="elasticsearch"

# ElasticSearch DETECT
[ -r /tmp/es00 ] || mkdir -p /tmp/es00
[ -r /tmp/es00 ] && (
  find /etc/$NAME -type f -follow > /tmp/es00/find.log;
  find /var/log/$NAME -type f -follow >> /tmp/es00/find.log;
  find /var/run -name "$NAME*" -type f -follow >> /tmp/es00/find.log;
  
  cat /tmp/es00/find.log;
)
 
cluster=$(grep "^cluster.name" </etc/elasticsearch/elasticsearch.yml | sed -e 's/ //g' | cut -d':' -f2); 
cluster=${cluster:=elasticsearch}; echo "$cluster"
node=$(grep "^node.name" </etc/elasticsearch/elasticsearch.yml | sed -e 's/ //g' | cut -d':' -f2); 
node=${node:=elasticsearch}; echo "$node";
port=$(grep "^port" </etc/elasticsearch/elasticsearch.yml | sed -e 's/ //g' | cut -d':' -f2);
port=${port:=9200}; echo "$port"

echo -e "# ===="
echo "curl -XGET http://${yourIP}:${port}/${cluster:=elasticsearch}/[type]/[_action/id]"
echo "curl -XGET http://${yourIP}:${port}/${node}-$(date +'%Y-%m-%d')/[type]/[_action/id]"
echo -e "# ===="
# PUT : create
curl -XPUT http://${yourIP}:${port}/twitter/tweet/1
echo "\tPUT empty"
curl -XGET http://${yourIP}:${port}/twitter/tweet/1
echo "\tGET"

curl -XPUT http://${yourIP}:${port}/twitter/tweet/1 -d '
{
"text": "Bienvenue à la conférence #elasticsearch pour #devoxxfr",
"created_at": "2012-04-06T20:45:36.000Z",
"source": "Twitter for android",
"truncated": false,
"retweet_count": 0,
"hashtag": [
{
"text": "elasticsearch",
"start": 27,
"end": 40
},
{
"text": "devoxxfr",
"start": 47,
"end": 55
}],
"user": {
"id": 51172224,
"name": "David Pilato",
"screen_name": "dadoonet",
"location": "France",
"description": "Soft Architect, Project Manager, Senior Developper"
}
}'
echo "\tPUT noEmpty"
curl -XGET http://${yourIP}:${port}/twitter/tweet/1
echo "\tGET"
# SEARCH
curl -XGET http://${yourIP}:${port}/twitter/tweet/_search
echo "\tSEARCH"
curl -XGET http://${yourIP}:${port}/twitter/_search
echo "\tSEARCH"
curl -XGET http://${yourIP}:${port}/_search
echo "\tSEARCH ALL"
curl -XGET http://${yourIP}:${port}/twitter/tweet/_search?q=elasticsearch
echo "\tSEARCH"
curl -XGET http://${yourIP}:${port}/twitter/tweet/_search?q=elasticsearch&from=10&size=10
echo "\tGET se balader de 10 en 10"
curl -XGET http://${yourIP}:${port}/twitter/twitter/_status
echo "\tMETADONNEES"
# DELETE
curl -XDELETE http://${yourIP}:${port}/twitter/tweet/1
echo "\tDELETE"
curl -XGET http://${yourIP}:${port}/twitter/tweet/1
echo "\tGET"


# NOUVELLE DONNEES
curl -X POST "http://${yourIP}:${port}/articles/article" -d '{"title" : "One", "tags" : ["foo"]}'
curl -X POST "http://${yourIP}:${port}/articles/article" -d '{"title" : "Two", "tags" : ["foo", "bar"]}'
curl -X POST "http://${yourIP}:${port}/articles/article" -d '{"title" : "Three", "tags" : ["foo", "bar", "baz"]}'
echo "\tPOST"

# FACET=term SEARCH
curl -X POST "http://${yourIP}:${port}/articles/_search?pretty=true" -d '
{
"query" : { "query_string" : {"query" : "T*"} },
"facets" : {
"tags" : { "terms" : {"field" : "tags"} }
}
}
'


# Creation index
curl -XPUT "http://${yourIP}:${port}/twitter" -d '{index : {number_of_shards: 2, number_of_replica: 1}}';
curl -XGET "http://${yourIP}:${port}/twitter/_search?q=elasticsearch";

# FACET=Date Histogram
# FACET=Ranges

# Cluster = n Nodes
# shard (lpar) (primary, index lucene)(secondary=replica primaire)
# replica = shard



exit 0;
