#!/bin/bash
#
# All error messages should go to STDERR.

export PATH='/usr/bin:'

#######################################
# Error messages
# Globals:
#   PATH_DIR
# Arguments:
#   None
# Returns:
#   None
#######################################
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

# if ! do_something; then
#  err "Unable to do_something"
#  exit "${E_DID_NOTHING}"
# fi

# TODO(etopaze): change the name file, use extension .sh only for the library (bug ####)
