#!/bin/bash
#
# All error messages should go to STDERR.

# All function comments should contain:
#    Description of the function
#    Global variables used and modified
#    Arguments taken
#    Returned values other than the default exit status of the last command run
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

# if ! do_something; then
#  err "Unable to do_something"
#  exit "${E_DID_NOTHING}"
# fi
