#!/bin/sh
#
# All error messages should go to STDERR.
# All other messages should go to STDOUT.

export PATH='/usr/bin:'

#######################################
# Out et Error messages
# Globals:
#   PATH_DIR
# Arguments:
#   None
# Returns:
#   None
#######################################
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

out() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&1
}

# if ! do_something; then
#  err "Unable to do_something"
#  exit "${E_DID_NOTHING}"
# else
#  out "info from something"
# fi

