#!/bin/sh
#
# All error messages should go to STDERR.
# All other messages should go to STDOUT.

# depends logger

export PATH='/usr/bin:'

#######################################
# Out et Error messages
# Globals:
#   PATH_DIR
# Arguments:
#   None
# Returns:
#   None
#######################################
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
}

out() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&1
}

# depends logger unix

# TODO : convention syslog : Security level
# 0 Emerg (emergency)       ⇒ Système inutilisable
# 1 Alert                   ⇒ Une intervention immédiate est nécessaire
# 2 Crit (critical)         ⇒ Erreur critique pour le système
# 3 Err (error)             ⇒ Erreur de fonctionnement
# 4 Warning                 ⇒ Avertissement
# 5 Notice                  ⇒ Événement normal méritant d'être signalé
# 6 Info (informational)    ⇒ pour information seulement
# 7 Debug                   ⇒ Message de mise au point

# TODO : Origine : type of message
# Numéro du Facilité   mot-clé 	Description
# 0 	kern 	kernel messages
# 1 	user 	user-level messages
# 2 	mail 	mail system
# 3 	daemon 	system daemons
# 4 	auth 	security/authorization messages
# 5 	syslog 	messages generated internally by syslogd
# 6 	lpr 	line printer subsystem
# 7 	news 	network news subsystem
# 8 	uucp 	UUCP subsystem
# 9 		clock daemon
# 10 	authpriv 	security/authorization messages
# 11 	ftp 	FTP daemon
# 12 	- 	NTP subsystem
# 13 	- 	log audit
# 14 	- 	log alert
# 15 	cron 	clock daemon
# 16 	local0 	local use 0 (local0)
# 17 	local1 	local use 1 (local1)
# 18 	local2 	local use 2 (local2)
# 19 	local3 	local use 3 (local3)
# 20 	local4 	local use 4 (local4)
# 21 	local5 	local use 5 (local5)
# 22 	local6 	local use 6 (local6)
# 23 	local7 	local use 7 (local7)

# if ! do_something; then
#  err "Unable to do_something"
#  exit "${E_DID_NOTHING}"
# else
#  out "info from something"
# fi

