about_Windows_PowerShell_ISE   Windows PowerShell ISE is a host application for Windows Pow...
More »
Add-Computer 	The Add-Computer cmdlet adds the local computer to a domain...
More »
Add-Content 	The Add-Content cmdlet appends content to a specified item o...
More »
Add-Content 	The Add-Content cmdlet appends content to a specified item o...
More »
Add-History 	The Add-History cmdlet adds entries to the end of the sessio...
More »
Add-Member 	The Add-Member cmdlet adds a user-defined custom member to a...
More »
Add-PSSnapin 	The Add-PSSnapin cmdlet adds registered Windows PowerShell s...
More »
Add-PSSnapin 	The Add-PSSnapin cmdlet adds registered Windows PowerShell s...
More »
Add-Type 	The Add-Type cmdlet lets you define a .NET Framework class i...
More »
Checkpoint-Computer 	The Checkpoint-Computer cmdlet creates a system restore poin...
More »
Clear-Content 	The Clear-Content cmdlet deletes the contents of an item, su...
More »
Clear-Content 	The Clear-Content cmdlet deletes the contents of an item, su...
More »
Clear-EventLog 	The Clear-EventLog cmdlet deletes all of the entries from th...
More »
Clear-History 	The Clear-History cmdlet deletes commands from the command h...
More »
Clear-History 	The Clear-History cmdlet deletes commands from the command h...
More »
Clear-Item 	The Clear-Item cmdlet deletes the value of an item, but it d...
More »
Clear-Item 	The Clear-Item cmdlet deletes the value of an item, but it d...
More »
Clear-ItemProperty 	The Clear-ItemProperty cmdlet deletes the value of a propert...
More »
Clear-ItemProperty 	The Clear-ItemProperty cmdlet deletes the value of a propert...
More »
Clear-Variable 	The Clear-Variable cmdlet deletes the data stored in a varia...
More »
Clear-Variable 	The Clear-Variable cmdlet deletes the data stored in a varia...
More »
Compare-Object 	The Compare-Object cmdlet compares two sets of objects. One...
More »
Compare-Object 	The Compare-Object cmdlet compares two sets of objects. One...
More »
Compare-Object 	The Compare-Object cmdlet compares two sets of objects. One...
More »
Complete-Transaction 	The Complete-Transaction cmdlet commits an active transactio...
More »
Connect-WSMan 	The Connect-WSMan cmdlet connects to the WinRM service on a...
More »
ConvertFrom-CSV 	The ConvertFrom-CSV cmdlet creates objects from CSV variable...
More »
ConvertFrom-SecureString 	The ConvertFrom-SecureString cmdlet converts a secure string...
More »
ConvertFrom-StringData 	The ConvertFrom-StringData cmdlet converts a string that con...
More »
Convert-Path 	The Convert-Path cmdlet converts a path from a Windows Power...
More »
Convert-Path 	The Convert-Path cmdlet converts a path from a Windows Power...
More »
ConvertTo-CSV 	The ConvertTo-CSV cmdlet returns a series of comma-separated...
More »
ConvertTo-Html 	The ConvertTo-Html cmdlet converts .NET Framework objects in...
More »
ConvertTo-SecureString 	The ConvertTo-SecureString cmdlet converts encrypted standar...
More »
ConvertTo-XML 	The ConvertTo-Xml cmdlet creates an XML-based representation...
More »
Copy-Item 	The Copy-Item cmdlet copies an item from one location to ano...
More »
Copy-Item 	The Copy-Item cmdlet copies an item from one location to ano...
More »
Copy-Item 	The Copy-Item cmdlet copies an item from one location to ano...
More »
Copy-Item 	The Copy-Item cmdlet copies an item from one location to ano...
More »
Copy-ItemProperty 	The Copy-ItemProperty cmdlet copies a property and value fro...
More »
Copy-ItemProperty 	The Copy-ItemProperty cmdlet copies a property and value fro...
More »
Debug-Process 	The Debug-Process cmdlet attaches a debugger to one or more...
More »
Disable-ComputerRestore 	The Disable-ComputerRestore cmdlet turns off the System Rest...
More »
Disable-PSBreakpoint 	The Disable-PSBreakpoint cmdlet disables breakpoints, which...
More »
Disable-PSBreakpoint 	The Disable-PSBreakpoint cmdlet disables breakpoints, which...
More »
Disable-PSRemoting 	...
More »
Disable-PSSessionConfiguration 	The Disable-PSSessionConfiguration cmdlet prevents all users...
More »
Disable-WSManCredSSP 	The Disable-WSManCredSPP cmdlet disables CredSSP authenticat...
More »
Disconnect-WSMan 	The Disconnect-WSMan cmdlet disconnects the client from the...
More »
Enable-ComputerRestore 	The Enable-ComputerRestore cmdlet turns on the System Restor...
More »
Enable-PSBreakpoint 	The Enable-PSBreakpoint cmdlet re-enables disabled breakpoin...
More »
Enable-PSBreakpoint 	The Enable-PSBreakpoint cmdlet re-enables disabled breakpoin...
More »
Enable-PSRemoting 	The Enable-PSRemoting cmdlet configures the computer to rece...
More »
Enable-PSSessionConfiguration 	The Enable-PSSessionConfiguration cmdlet re-enables register...
More »
Enable-WSManCredSSP 	The Enable-WSManCredSPP cmdlet enables CredSSP authenticatio...
More »
Enter-PSSession 	The Enter-PSSession cmdlet starts an interactive session wit...
More »
Enter-PSSession 	The Enter-PSSession cmdlet starts an interactive session wit...
More »
Exit-PSSession 	The Exit-PSSession cmdlet ends interactive sessions that you...
More »
Exit-PSSession 	The Exit-PSSession cmdlet ends interactive sessions that you...
More »
Export-Alias 	The Export-Alias cmdlet exports the aliases in the current s...
More »
Export-Alias 	The Export-Alias cmdlet exports the aliases in the current s...
More »
Export-Clixml 	The Export-Clixml cmdlet creates an XML-based representation...
More »
Export-Console 	The Export-Console cmdlet exports the names of the Windows P...
More »
Export-Counter 	The Export-Counter cmdlet exports performance counter data (...
More »
Export-CSV 	The Export-CSV cmdlet creates a CSV variable-length file tha...
More »
Export-CSV 	The Export-CSV cmdlet creates a CSV variable-length file tha...
More »
Export-FormatData 	The Export-FormatData cmdlet creates Windows PowerShell form...
More »
Export-ModuleMember 	The Export-ModuleMember cmdlet specifies the module members...
More »
Export-PSSession 	The Export-PSSession cmdlet gets cmdlets, functions, aliases...
More »
Export-PSSession 	The Export-PSSession cmdlet gets cmdlets, functions, aliases...
More »
ForEach-Object 	The ForEach-Object cmdlet performs an operation on each of a...
More »
ForEach-Object 	The ForEach-Object cmdlet performs an operation on each of a...
More »
ForEach-Object 	The ForEach-Object cmdlet performs an operation on each of a...
More »
Format-Custom 	The Format-Custom cmdlet formats the output of a command as...
More »
Format-Custom 	The Format-Custom cmdlet formats the output of a command as...
More »
Format-List 	The Format-List cmdlet formats the output of a command as a...
More »
Format-List 	The Format-List cmdlet formats the output of a command as a...
More »
Format-Table 	Format-Table [[-Property] <Object[]>] [-AutoSize] [-Displ...
More »
Format-Table 	The Format-Table cmdlet formats the output of a command as a...
More »
Format-Wide 	The Format-Wide cmdlet formats objects as a wide table that...
More »
Format-Wide 	The Format-Wide cmdlet formats objects as a wide table that...
More »
Get-Acl 	The Get-Acl cmdlet gets objects that represent the security...
More »
Get-Alias 	The Get-Alias cmdlet gets the aliases (alternate names for c...
More »
Get-Alias 	The Get-Alias cmdlet gets the aliases (alternate names for c...
More »
Get-AuthenticodeSignature 	The Get-AuthenticodeSignature cmdlet gets information about...
More »
Get-ChildItem 	The Get-ChildItem cmdlet gets the items in one or more speci...
More »
Get-ChildItem 	The Get-ChildItem cmdlet gets the items in one or more speci...
More »
Get-ChildItem 	The Get-ChildItem cmdlet gets the items in one or more speci...
More »
Get-ChildItem 	The Get-ChildItem cmdlet gets the items in one or more speci...
More »
Get-Command 	The Get-Command cmdlet gets basic information about cmdlets...
More »
Get-Command 	The Get-Command cmdlet gets basic information about cmdlets...
More »
Get-ComputerRestorePoint 	The Get-ComputerRestorePoint cmdlet gets the restore points...
More »
Get-Content 	The Get-Content cmdlet gets the content of the item at the l...
More »
Get-Content 	The Get-Content cmdlet gets the content of the item at the l...
More »
Get-Content 	The Get-Content cmdlet gets the content of the item at the l...
More »
Get-Content 	The Get-Content cmdlet gets the content of the item at the l...
More »
Get-Counter 	The Get-Counter cmdlet gets live, real-time performance coun...
More »
Get-Credential 	The Get-Credential cmdlet creates a credential object for a...
More »
Get-Culture 	The Get-Culture cmdlet gets information about the current cu...
More »
Get-Date 	The Get-Date cmdlet gets a DateTime object that represents t...
More »
Get-Event 	The Get-Event cmdlet gets events in the Windows PowerShell e...
More »
Get-EventLog 	The Get-EventLog cmdlet gets events and event logs on the lo...
More »
Get-EventSubscriber 	The Get-EventSubscriber cmdlet gets the event subscribers in...
More »
Get-ExecutionPolicy 	The Get-ExecutionPolicy cmdlet gets the execution policies f...
More »
Get-FormatData 	The Get-FormatData cmdlet gets the formatting data in the cu...
More »
Get-Help 	The Get-Help cmdlet displays information about Windows Power...
More »
Get-Help 	The Get-Help cmdlet displays information about Windows Power...
More »
Get-Help 	The Get-Help cmdlet displays information about Windows Power...
More »
Get-History 	The Get-History cmdlet gets the session history, that is, th...
More »
Get-History 	The Get-History cmdlet gets the session history, that is, th...
More »
Get-History 	The Get-History cmdlet gets the session history, that is, th...
More »
Get-History 	The Get-History cmdlet gets the session history, that is, th...
More »
Get-Host 	The Get-Host cmdlet gets an object that represents the progr...
More »
Get-HotFix 	The Get-Hotfix cmdlet gets the hotfixes that have been appli...
More »
Get-Item 	cThe Get-Item cmdlet gets the item at the specified location...
More »
Get-Item 	The Get-Item cmdlet gets the item at the specified location....
More »
Get-ItemProperty 	The Get-ItemProperty cmdlet gets the properties of the speci...
More »
Get-ItemProperty 	The Get-ItemProperty cmdlet gets the properties of the speci...
More »
Get-Job 	The Get-Job cmdlet gets objects that represent the backgroun...
More »
Get-Job 	The Get-Job cmdlet gets objects that represent the backgroun...
More »
Get-Location 	The Get-Location cmdlet gets an object that represents the c...
More »
Get-Location 	The Get-Location cmdlet gets an object that represents the c...
More »
Get-Location 	The Get-Location cmdlet gets an object that represents the c...
More »
Get-Member 	The Get-Member cmdlet gets the "members" (properties and met...
More »
Get-Member 	The Get-Member cmdlet gets the "members" (properties and met...
More »
Get-Module 	The Get-Module cmdlet gets the modules that have been import...
More »
Get-Module 	The Get-Module cmdlet gets the modules that have been import...
More »
Get-PfxCertificate 	The Get-PfxCertificate cmdlet gets an object representing ea...
More »
Get-Process 	The Get-Process cmdlet gets the processes on a local or remo...
More »
Get-Process 	The Get-Process cmdlet gets the processes on a local or remo...
More »
Get-Process 	The Get-Process cmdlet gets the processes on a local or remo...
More »
Get-PSBreakpoint 	The Get-PSBreakPoint cmdlet gets the breakpoints that are se...
More »
Get-PSBreakpoint 	The Get-PSBreakPoint cmdlet gets the breakpoints that are se...
More »
Get-PSCallStack 	The Get-PSCallStack cmdlet displays the current call stack....
More »
Get-PSCallStack 	The Get-PSCallStack cmdlet displays the current call stack....
More »
Get-PSDrive 	The Get-PSDrive cmdlet gets the Windows PowerShell drives in...
More »
Get-PSDrive 	The Get-PSDrive cmdlet gets the Windows PowerShell drives in...
More »
Get-PSProvider 	The Get-PSProvider cmdlet gets the Windows PowerShell provid...
More »
Get-PSSession 	The Get-PSSession cmdlet gets the Windows PowerShell session...
More »
Get-PSSession 	The Get-PSSession cmdlet gets the Windows PowerShell session...
More »
Get-PSSessionConfiguration 	The Get-PSSessionConfiguration cmdlet gets the session confi...
More »
Get-PSSnapin 	The Get-PSSnapin cmdlet gets the Windows PowerShell snap-ins...
More »
Get-PSSnapin 	The Get-PSSnapin cmdlet gets the Windows PowerShell snap-ins...
More »
Get-Random 	The Get-Random cmdlet gets a randomly selected number. If yo...
More »
Get-Service 	The Get-Service cmdlet gets objects that represent the servi...
More »
Get-Service 	The Get-Service cmdlet gets objects that represent the servi...
More »
Get-TraceSource 	The Get-TraceSource cmdlet gets the trace sources for Window...
More »
Get-Transaction 	The Get-Transaction cmdlet gets an object that represents th...
More »
Get-UICulture 	The Get-UICulture cmdlet gets information about the current...
More »
Get-Unique 	The Get-Unique cmdlet compares each item in a sorted list to...
More »
Get-Unique 	The Get-Unique cmdlet compares each item in a sorted list to...
More »
Get-Variable 	The Get-Variable cmdlet gets the Windows PowerShell variable...
More »
Get-Variable 	The Get-Variable cmdlet gets the Windows PowerShell variable...
More »
Get-WinEvent 	The Get-WinEvent cmdlet gets events from event logs, includi...
More »
Get-WmiObject 	The Get-WmiObject cmdlet gets instances of WMI classes or in...
More »
Get-WmiObject 	The Get-WmiObject cmdlet gets instances of WMI classes or in...
More »
Get-WSManCredSSP 	The Get-WSManCredSPP cmdlet gets the Credential Security Ser...
More »
Get-WSManInstance 	The Get-WSManInstance cmdlet retrieves an instance of a mana...
More »
Group-Object 	The Group-Object cmdlet displays objects in groups based on...
More »
Group-Object 	The Group-Object cmdlet displays objects in groups based on...
More »
Import-Alias 	The Import-Alias cmdlet imports an alias list from a file.
More »
Import-Alias 	The Import-Alias cmdlet imports an alias list from a file.
More »
Import-Clixml 	The Import-Clixml cmdlet imports a CLIXML file with data tha...
More »
Import-Counter 	The Import-Counter cmdlet imports performance counter data f...
More »
Import-CSV 	The Import-CSV cmdlet creates objects from CSV variable-leng...
More »
Import-CSV 	The Import-CSV cmdlet creates objects from CSV variable-leng...
More »
Import-LocalizedData 	The Import-LocalizedData cmdlet dynamically retrieves string...
More »
Import-Module 	The Import-Module cmdlet adds one or more modules to the cur...
More »
Import-Module 	The Import-Module cmdlet adds one or more modules to the cur...
More »
Import-PSSession 	The Import-PSSession cmdlet imports commands (such as cmdlet...
More »
Import-PSSession 	The Import-PSSession cmdlet imports commands (such as cmdlet...
More »
Invoke-Command 	The Invoke-Command cmdlet runs commands on a local or remote...
More »
Invoke-Command 	The Invoke-Command cmdlet runs commands on a local or remote...
More »
Invoke-Expression 	The Invoke-Expression cmdlet evaluates or runs a specified s...
More »
Invoke-Expression 	The Invoke-Expression cmdlet evaluates or runs a specified s...
More »
Invoke-History 	The Invoke-History cmdlet runs commands from the session his...
More »
Invoke-History 	The Invoke-History cmdlet runs commands from the session his...
More »
Invoke-History 	The Invoke-History cmdlet runs commands from the session his...
More »
Invoke-Item 	The Invoke-Item cmdlet performs the default action on the sp...
More »
Invoke-Item 	The Invoke-Item cmdlet performs the default action on the sp...
More »
Invoke-WmiMethod 	The Invoke-WmiMethod cmdlet calls WMI methods.
More »
Invoke-WmiMethod 	The Invoke-WmiMethod cmdlet calls WMI methods.
More »
Invoke-WSManAction 	The Invoke-WSManAction runs an action on the object that is...
More »
Join-Path 	The Join-Path cmdlet combines a path and child-path into a s...
More »
Limit-EventLog 	The Limit-EventLog cmdlet sets the maximum size of a classic...
More »
Measure-Command 	The Measure-Command cmdlet runs a script block or cmdlet int...
More »
Measure-Command 	The Measure-Command cmdlet runs a script block or cmdlet int...
More »
Measure-Object 	The Measure-Object cmdlet calculates the property values of...
More »
Measure-Object 	The Measure-Object cmdlet calculates the property values of...
More »
Measure-Object 	The Measure-Object cmdlet calculates the property values of...
More »
Move-Item 	The Move-Item cmdlet moves an item, including its properties...
More »
Move-Item 	The Move-Item cmdlet moves an item, including its properties...
More »
Move-Item 	The Move-Item cmdlet moves an item, including its properties...
More »
Move-Item 	The Move-Item cmdlet moves an item, including its properties...
More »
Move-ItemProperty 	The Move-ItemProperty cmdlet moves a property of an item fro...
More »
Move-ItemProperty 	The Move-ItemProperty cmdlet moves a property of an item fro...
More »
New-Alias 	The New-Alias cmdlet creates a new alias in the current Wind...
More »
New-Alias 	The New-Alias cmdlet creates a new alias in the current Wind...
More »
New-Event 	The New-Event cmdlet creates a new custom event. You can...
More »
New-EventLog 	This cmdlet creates a new classic event log on a local or re...
More »
New-Item 	The New-Item cmdlet creates a new item and sets its value. T...
More »
New-Item 	The New-Item cmdlet creates a new item and sets its value. T...
More »
New-Item 	The New-Item cmdlet creates a new item and sets its value. T...
More »
New-Item 	The New-Item cmdlet creates a new item and sets its value. T...
More »
New-ItemProperty 	The New-ItemProperty cmdlet creates a new property for a spe...
More »
New-Module 	The New-Module cmdlet creates a dynamic module from a script...
More »
New-Module 	The New-Module cmdlet creates a dynamic module from a script...
More »
New-ModuleManifest 	The New-ModuleManifest cmdlet creates a new module manifest...
More »
New-Object 	The New-Object cmdlet creates an instance of a .NET Framewor...
More »
New-PSDrive 	The New-PSDrive cmdlet creates a Windows PowerShell drive th...
More »
New-PSDrive 	The New-PSDrive cmdlet creates a Windows PowerShell drive th...
More »
New-PSDrive 	The New-PSDrive cmdlet creates a Windows PowerShell drive th...
More »
New-PSSession 	The New-PSSession cmdlet creates a Windows PowerShell sessio...
More »
New-PSSession 	The New-PSSession cmdlet creates a Windows PowerShell sessio...
More »
New-PSSessionOption 	The New-PSSessionOption cmdlet creates an object that contai...
More »
New-Service 	The New-Service cmdlet creates a new entry for a Windows ser...
More »
New-TimeSpan 	The New-TimeSpan cmdlet creates a TimeSpan object that repre...
More »
New-Variable 	The New-Variable cmdlet creates a new variable in Windows Po...
More »
New-Variable 	The New-Variable cmdlet creates a new variable in Windows Po...
More »
New-WebServiceProxy 	The New-WebServiceProxy cmdlet lets you use a Web service in...
More »
New-WSManInstance 	The New-WSManInstance cmdlet creates a new instance of a man...
More »
New-WSManSessionOption 	Creates a WSMan Session option hashtable which can be passed...
More »
Out-Default 	The Out-Default cmdlet sends output to the default formatter...
More »
Out-File 	The Out-File cmdlet sends output to a file. You can use this...
More »
Out-GridView 	The Out-GridView cmdlet sends the output from a command to a...
More »
Out-GridView 	The Out-GridView cmdlet sends the output from a command to a...
More »
Out-Host 	The Out-Host cmdlet sends output to the Windows PowerShell h...
More »
Out-Host 	The Out-Host cmdlet sends output to the Windows PowerShell h...
More »
Out-Null 	The Out-Null cmdlet sends output to NULL, in effect, deletin...
More »
Out-Printer 	Out-Printer [[-Name] <string>] [-InputObject <psobject...
More »
Out-Printer 	The Out-Printer cmdlet sends output to the default printer o...
More »
Out-String 	The Out-String cmdlet converts the objects that Windows Powe...
More »
Pop-Location 	The Pop-Location cmdlet changes the current location to the...
More »
Pop-Location 	The Pop-Location cmdlet changes the current location to the...
More »
Push-Location 	The Push-Location cmdlet adds ("pushes") the current locatio...
More »
Push-Location 	The Push-Location cmdlet adds ("pushes") the current locatio...
More »
Read-Host 	The Read-Host cmdlet reads a line of input from the console....
More »
Receive-Job 	The Receive-Job cmdlet gets the results of Windows Powershel...
More »
Receive-Job 	The Receive-Job cmdlet gets the results of Windows Powershel...
More »
Register-EngineEvent 	The Register-EngineEvent cmdlet subscribes to events that ar...
More »
Register-ObjectEvent 	The Register-ObjectEvent cmdlet subscribes to events that ar...
More »
Register-PSSessionConfiguration 	The Register-PSSessionConfiguration cmdlet creates and regis...
More »
Register-WmiEvent 	The Register-WmiEvent cmdlet subscribes to WMI events on the...
More »
Remove-Computer 	The Remove-Computer cmdlet removes the local computer from i...
More »
Remove-Event 	The Remove-Event cmdlet deletes events from the event queue...
More »
Remove-EventLog 	The Remove-EventLog cmdlet deletes an event log file from a...
More »
Remove-Item 	The Remove-Item cmdlet deletes one or more items. Because it...
More »
Remove-Item 	The Remove-Item cmdlet deletes one or more items. Because it...
More »
Remove-Item 	The Remove-Item cmdlet deletes one or more items. Because it...
More »
Remove-Item 	The Remove-Item cmdlet deletes one or more items. Because it...
More »
Remove-Item 	The Remove-Item cmdlet deletes one or more items. Because it...
More »
Remove-Item 	The Remove-Item cmdlet deletes one or more items. Because it...
More »
Remove-Item 	The Remove-Item cmdlet deletes one or more items. Because it...
More »
Remove-ItemProperty 	The Remove-ItemProperty cmdlet deletes a property and its va...
More »
Remove-ItemProperty 	The Remove-ItemProperty cmdlet deletes a property and its va...
More »
Remove-Job 	The Remove-Job cmdlet deletes Windows PowerShell background...
More »
Remove-Job 	The Remove-Job cmdlet deletes Windows PowerShell background...
More »
Remove-Module 	The Remove-Module cmdlet removes the members of a module fro...
More »
Remove-Module 	The Remove-Module cmdlet removes the members of a module fro...
More »
Remove-PSBreakpoint 	The Remove-PSBreakpoint cmdlet deletes a breakpoint. Enter a...
More »
Remove-PSBreakpoint 	The Remove-PSBreakpoint cmdlet deletes a breakpoint. Enter a...
More »
Remove-PSDrive 	The Remove-PSDrive cmdlet deletes Windows PowerShell drives...
More »
Remove-PSDrive 	The Remove-PSDrive cmdlet deletes Windows PowerShell drives...
More »
Remove-PSSession 	The Remove-PSSession cmdlet closes Windows PowerShell sessio...
More »
Remove-PSSession 	The Remove-PSSession cmdlet closes Windows PowerShell sessio...
More »
Remove-PSSnapin 	The Remove-PSSnapin cmdlet removes a Windows PowerShell snap...
More »
Remove-PSSnapin 	The Remove-PSSnapin cmdlet removes a Windows PowerShell snap...
More »
Remove-Variable 	The Remove-Variable cmdlet deletes a variable and its value...
More »
Remove-Variable 	The Remove-Variable cmdlet deletes a variable and its value...
More »
Remove-WmiObject 	The Remove-WmiObject cmdlet deletes an instance of an existi...
More »
Remove-WmiObject 	The Remove-WmiObject cmdlet deletes an instance of an existi...
More »
Remove-WSManInstance 	The Remove-WSManInstance deletes an instance of a management...
More »
Rename-Item 	The Rename-Item cmdlet changes the name of a specified item....
More »
Rename-Item 	The Rename-Item cmdlet changes the name of a specified item....
More »
Rename-Item 	The Rename-Item cmdlet changes the name of a specified item....
More »
Rename-ItemProperty 	The Rename-ItemProperty cmdlet changes the name of a specifi...
More »
Rename-ItemProperty 	The Rename-ItemProperty cmdlet changes the name of a specifi...
More »
Reset-ComputerMachinePassword 	The Reset-ComputerMachinePassword cmdlet changes the machine...
More »
Resolve-Path 	The Resolve-Path cmdlet interprets the wildcard characters i...
More »
Resolve-Path 	The Resolve-Path cmdlet interprets the wildcard characters i...
More »
Restart-Computer 	The Restart-Computer cmdlet restarts the operating system on...
More »
Restart-Service 	The Restart-Service cmdlet sends a stop message and then a s...
More »
Restore-Computer 	The Restore-Computer cmdlet restores the local computer to t...
More »
Resume-Service 	The Resume-Service cmdlet sends a resume message to the Wind...
More »
Select-Object 	The Select-Object cmdlet gets only the specified properties...
More »
Select-Object 	The Select-Object cmdlet gets only the specified properties...
More »
Select-String 	The Select-String cmdlet searches for text and text patterns...
More »
Select-XML 	The Select-XML cmdlet lets you use XPath queries to search f...
More »
Send-MailMessage 	The Send-MailMessage cmdlet sends an e-mail message from wit...
More »
Set-Acl 	The Set-Acl cmdlet changes the security descriptor of a spec...
More »
Set-Alias 	The Set-Alias cmdlet creates or changes an alias (alternate...
More »
Set-Alias 	The Set-Alias cmdlet creates or changes an alias (alternate...
More »
Set-AuthenticodeSignature 	The Set-AuthenticodeSignature cmdlet adds an Authenticode si...
More »
Set-Content 	The Set-Content cmdlet is a string-processing cmdlet that wr...
More »
Set-Content 	The Set-Content cmdlet is a string-processing cmdlet that wr...
More »
Set-Date 	The Set-Date cmdlet changes the system date and time on the...
More »
Set-ExecutionPolicy 	The Set-ExecutionPolicy changes the user preference for the...
More »
Set-Item 	The Set-Item cmdlet changes the value of an item, such as a...
More »
Set-Item 	The Set-Item cmdlet changes the value of an item, such as a...
More »
Set-ItemProperty 	The Set-ItemProperty cmdlet changes the value of the propert...
More »
Set-ItemProperty 	The Set-ItemProperty cmdlet changes the value of the propert...
More »
Set-Location 	The Set-Location cmdlet sets the working location to a speci...
More »
Set-Location 	The Set-Location cmdlet sets the working location to a speci...
More »
Set-Location 	The Set-Location cmdlet sets the working location to a speci...
More »
Set-Location 	The Set-Location cmdlet sets the working location to a speci...
More »
Set-PSBreakpoint 	The Set-PSBreakpoint cmdlet sets a breakpoint in a script or...
More »
Set-PSBreakpoint 	The Set-PSBreakpoint cmdlet sets a breakpoint in a script or...
More »
Set-PSDebug 	The Set-PSDebug cmdlet turns script debugging features on an...
More »
Set-PSSessionConfiguration 	Set-PSSessionConfiguration [-AssemblyName] <string> [-Con...
More »
Set-Service 	The Set-Service cmdlet changes the properties of a local or...
More »
Set-StrictMode 	The Set-StrictMode cmdlet configures strict mode for the cur...
More »
Set-TraceSource 	The Set-TraceSource cmdlet configures, starts, and stops a t...
More »
Set-Variable 	The Set-Variable cmdlet assigns a value to a specified varia...
More »
Set-Variable 	The Set-Variable cmdlet assigns a value to a specified varia...
More »
Set-Variable 	The Set-Variable cmdlet assigns a value to a specified varia...
More »
Set-WmiInstance 	The Set-WmiInstance cmdlet creates or updates an instance of...
More »
Set-WmiInstance 	The Set-WmiInstance cmdlet creates or updates an instance of...
More »
Set-WSManInstance 	The Set-WSManInstance cmdlet modifies the management informa...
More »
Set-WSManQuickConfig 	The Set-WSManQuickConfig cmdlet configures the computer to r...
More »
Show-EventLog 	The Show-EventLog cmdlet opens Event Viewer on the local com...
More »
Sort-Object 	The Sort-Object cmdlet sorts objects in ascending or descend...
More »
Sort-Object 	The Sort-Object cmdlet sorts objects in ascending or descend...
More »
Split-Path 	The Split-Path cmdlet returns only the specified part of a p...
More »
Start-Job 	The Start-Job cmdlet starts a Windows PowerShell background...
More »
Start-Job 	The Start-Job cmdlet starts a Windows PowerShell background...
More »
Start-Process 	Starts one or more processes on the local computer. To spec...
More »
Start-Process 	Starts one or more processes on the local computer. To spec...
More »
Start-Process 	Starts one or more processes on the local computer. To spec...
More »
Start-Service 	The Start-Service cmdlet sends a start message to the Window...
More »
Start-Service 	The Start-Service cmdlet sends a start message to the Window...
More »
Start-Sleep 	The Start-Sleep cmdlet suspends the activity in a script or...
More »
Start-Sleep 	The Start-Sleep cmdlet suspends the activity in a script or...
More »
Start-Transaction 	The Start-Transaction cmdlet starts a transaction, which is...
More »
Start-Transcript 	The Start-Transcript cmdlet creates a record of all or part...
More »
Stop-Computer 	The Stop-Computer cmdlet shuts down computers remotely. It c...
More »
Stop-Job 	The Stop-Job cmdlet stops Windows PowerShell background jobs...
More »
Stop-Job 	The Stop-Job cmdlet stops Windows PowerShell background jobs...
More »
Stop-Process 	The Stop-Process cmdlet stops one or more running processes....
More »
Stop-Process 	The Stop-Process cmdlet stops one or more running processes....
More »
Stop-Process 	The Stop-Process cmdlet stops one or more running processes....
More »
Stop-Service 	The Stop-Service cmdlet sends a stop message to the Windows...
More »
Stop-Service 	The Stop-Service cmdlet sends a stop message to the Windows...
More »
Stop-Transcript 	The Stop-Transcript cmdlet stops a transcript that was start...
More »
Suspend-Service 	The Suspend-Service cmdlet sends a suspend message to the Wi...
More »
Tee-Object 	The Tee-Object cmdlet sends the output of a command in two d...
More »
Tee-Object 	The Tee-Object cmdlet sends the output of a command in two d...
More »
Test-ComputerSecureChannel 	The Test-ComputerSecureChannel cmdlet verifies that the secu...
More »
Test-Connection 	The Test-Connection cmdlet sends Internet Control Message Pr...
More »
Test-ModuleManifest 	The Test-ModuleManifest cmdlet verifies that the files that...
More »
Test-Path 	The Test-Path cmdlet determines whether all elements of the...
More »
Test-WSMan 	The Test-WSMan cmdlet submits an identification request that...
More »
Trace-Command 	The Trace-Command cmdlet configures and starts a trace of th...
More »
Undo-Transaction 	The Undo-Transaction cmdlet rolls back the active transactio...
More »
Unregister-Event 	The Unregister-Event cmdlet cancels an event subscription th...
More »
Unregister-PSSessionConfiguration 	The Unregister-PSSessionConfiguration cmdlet deletes registe...
More »
Update-FormatData 	The Update-FormatData cmdlet reloads the formatting data fro...
More »
Update-List 	The Update-List cmdlet adds items to and removes items from...
More »
Update-TypeData 	The Update-TypeData cmdlet updates the current extended type...
More »
Use-Transaction 	The Use-Transaction cmdlet adds a script block to an active...
More »
Wait-Event 	The Wait-Event cmdlet suspends execution of a script or func...
More »
Wait-Job 	The Wait-Job cmdlet waits for Windows PowerShell background...
More »
Wait-Job 	The Wait-Job cmdlet waits for Windows PowerShell background...
More »
Wait-Process 	The Wait-Process cmdlet waits for one or more running proces...
More »
Where-Object 	The Where-Object cmdlet selects objects from the set of obje...
More »
Where-Object 	The Where-Object cmdlet selects objects from the set of obje...
More »
Write-Debug 	The Write-Debug cmdlet writes debug messages to the console...
More »
Write-Error 	The Write-Error cmdlet writes an error to the Windows PowerS...
More »
Write-EventLog 	The Write-EventLog cmdlet writes an event to an event log. ...
More »
Write-Host 	The Write-Host cmdlet customizes output. You can specify the...
More »
Write-Output 	The Write-Output cmdlet sends the specified object down the...
More »
Write-Output 	The Write-Output cmdlet sends the specified object down the...
More »
Write-Output 	The Write-Output cmdlet sends the specified object down the...
More »
Write-Progress 	The Write-Progress cmdlet displays a progress bar in a Windo...
More »
Write-Verbose 	The Write-Verbose cmdlet writes text to the verbose message...
More »
Write-Warning 	The Write-Warning cmdlet writes a warning message to the Win...
More »
